### ISSUE TITLE
MDL project?

### ISSUE THREAD

**Issue by arlair** [CyclicMaterials/cyclicmaterials#2]
Hi, I was interested to know if you have investigated leveraging the large effort going into the Material Design Lite library and wrapping it with Cycle.js components?

https://github.com/google/material-design-lite

I did some basic testing with a slider and text input and ran into some issues, but I think they were mainly to do with MDL bugs. Slider in particular sounds like it will be rewritten in MDL 2.0 with divs due to browser issues trying to override the native input slider.

Are there any issues you know of using MDL that made you go down the totally custom route?

Cheers.

**Comment by Frikki** [comment]
@arlair Indeed, there are resons. One being that MDL needs to run JavaScript that that modifies the DOM.
